### ISSUE TITLE
Setting default parameter as nil

### ISSUE THREAD

**Issue by azzahidK** [abiwinanda/fictitious#3]
I can't set a parameter to be nil it's always filled with something.
Is there a way to make it nil ?

**Comment by abiwinanda** [comment]
Yes you could find it in the following docs at the ` Giving Null Value` section [https://hexdocs.pm/fictitious/Fictitious.html](https://hexdocs.pm/fictitious/Fictitious.html)

in summary you pass `:null` to set a field value with `nil`

```elixir
{:ok, _} = Fictitious.fictionize(SomeSchema, some_field: :null)
```
